spark.jars.packages                         org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262

# Koneksi MinIO via S3A
spark.hadoop.fs.s3a.endpoint               http://minio:9000
spark.hadoop.fs.s3a.access.key             minioadmin
spark.hadoop.fs.s3a.secret.key             minioadmin
spark.hadoop.fs.s3a.path.style.access      true
spark.hadoop.fs.s3a.impl                   org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled false

# Hive Metastore
spark.sql.catalogImplementation            hive
spark.hadoop.hive.metastore.uris           thrift://hive-metastore:9083
spark.sql.warehouse.dir                    s3a://bigdata/warehouse

# Performance — sesuaikan dengan RAM PC kalian
spark.sql.shuffle.partitions               10
spark.driver.memory                        2g
spark.executor.memory                      2g